### ISSUE TITLE
sendmail question

### ISSUE THREAD

**Issue by bmaca** [NinjaSl0th/nixupdater#1]
@NinjaSl0th 
If sendmail is installed, cant you just replace ```/bin/mail -s``` with just ```sendmail -s``` ?

**Comment by NinjaSl0th** [comment]
In the case of my setup i was using /bin/mail -s 

However, I have not tested using just ```sendmail -s```

**Comment by bmaca** [comment]
@NinjaSl0th That was my though :). Worked foe me with ```mail -s```
Cool thanks. I will close
